### ISSUE TITLE
Continuous requests sometimes cause a 'Reel::StateError: not in chunked body mode' error

### ISSUE THREAD

**Issue by runningferret** [celluloid/reel#161]
We have an app that, among other things, runs Reel/Sinatra. The main application is a voice app primarily based on [Adhearsion](https://github.com/adhearsion/adhearsion), and it uses a plugin of sorts called [Virginia](https://github.com/polysics/virginia/) to run Reel and Sinatra, providing a web-interface for us.

We have one machine in our development environment that gets hit with a 'health check' over HTTP ever 15 seconds. On seemingly random occasions we don't see the regular log after 15s, and then Reel crashed:

```
192.168.10.8 - - [05/Nov/2014 17:47:22] "GET /status " 200 28 0.0060
192.168.10.8 - - [05/Nov/2014 17:47:37] "GET /status " 200 28 0.0070
[2014-11-05 17:48:08] ERROR Celluloid: Reel::Rack::Server crashed!
Reel::StateError: not in chunked body mode
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/request.rb:94:in `write'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:47:in `route_request'
org/jruby/RubyArray.java:1617:in `each'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/rack-1.4.5/lib/rack/body_proxy.rb:31:in `each'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:47:in `route_request'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:29:in `on_connection'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/connection.rb:73:in `each_request'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:25:in `on_connection'
org/jruby/RubyMethod.java:134:in `call'
org/jruby/RubyProc.java:255:in `call'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/server.rb:56:in `handle_connection'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/server.rb:55:in `handle_connection'
org/jruby/RubyBasicObject.java:1730:in `__send__'
org/jruby/RubyKernel.java:1932:in `public_send'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `handle_message'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `task'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `initialize'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:47:in `initialize'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `create'
[2014-11-05 17:48:08] ERROR Adhearsion::Initializer: <Reel::StateError> not in chunked body mode
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/request.rb:94:in `write'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:47:in `route_request'
org/jruby/RubyArray.java:1617:in `each'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/rack-1.4.5/lib/rack/body_proxy.rb:31:in `each'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:47:in `route_request'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:29:in `on_connection'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/connection.rb:73:in `each_request'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:25:in `on_connection'
org/jruby/RubyMethod.java:134:in `call'
org/jruby/RubyProc.java:255:in `call'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/server.rb:56:in `handle_connection'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/server.rb:55:in `handle_connection'
org/jruby/RubyBasicObject.java:1730:in `__send__'
org/jruby/RubyKernel.java:1932:in `public_send'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `handle_message'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `task'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `initialize'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:47:in `initialize'
/srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `create'
[2014-11-05 17:48:08] WARN  Celluloid: Terminating task: type=:call, meta={:method_name=>:run}, status=:iowait
[2014-11-05 17:48:08] INFO  Celluloid: A Reel good HTTP server! (Codename "Bette")
[2014-11-05 17:48:08] INFO  Celluloid: Listening on http://0.0.0.0:5005
```

As you can see, the first lines are the regular 15s intervals. The timestamp at the crash is 30 seconds later, hence the one missing log line. Reel restarted right away and continue to serve requests.

We thought this was a freak occurrence due to some issue with our load balancer that issues that HTTP health-check, but we have since seen this happen multiple times.

Given [the location of the error](https://github.com/celluloid/reel/blob/master/lib/reel/request.rb#L94) in Reel, I assume there is a bug with either how the state machine transfers to the `:chunked_body` state, or with how the load-balancer issues/handles the HTTP health-check. While we currently do not hit any web-based endpoints during our call processing, we might want to in the future, and having this occur would cause the call to crash, which would be pretty undesirable for us.

Any thoughts on how we might avoid this issue, or avenues to diagnose better? As an aside, we are currently pinned to celluloid 0.15.2 due to an issue with a [Punchblock](https://github.com/adhearsion/punchblock) and cannot upgrade to 0.16.x yet.

**Comment by digitalextremist** [comment]
I'm removing this from `0.6.0` because I need a repro. Please post a repro and I'll get it in `0.6.5`
