### ISSUE TITLE
Reel is broken after http v0.8.0 has been released.

### ISSUE THREAD

**Issue by SaitoWu** [celluloid/reel#185]
```bash
› linner w
/Users/saito/.rvm/gems/ruby-2.2.0/gems/http-0.8.0/lib/http/timeout/per_operation.rb:4:in `<class:PerOperation>': uninitialized constant HTTP::Timeout::PerOperation::Resolv (NameError)
	from /Users/saito/.rvm/gems/ruby-2.2.0/gems/http-0.8.0/lib/http/timeout/per_operation.rb:3:in `<module:Timeout>'
	from /Users/saito/.rvm/gems/ruby-2.2.0/gems/http-0.8.0/lib/http/timeout/per_operation.rb:2:in `<module:HTTP>'
	from /Users/saito/.rvm/gems/ruby-2.2.0/gems/http-0.8.0/lib/http/timeout/per_operation.rb:1:in `<top (required)>'
	from /Users/saito/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/saito/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/saito/.rvm/gems/ruby-2.2.0/gems/http-0.8.0/lib/http.rb:5:in `<top (required)>'
	from /Users/saito/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/saito/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/saito/.rvm/gems/ruby-2.2.0/gems/reel-0.5.0/lib/reel.rb:4:in `<top (required)>'
	from /Users/saito/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/saito/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/saito/.rvm/gems/ruby-2.2.0/gems/linner-0.9.1/lib/linner/reactor.rb:1:in `<top (required)>'
	from /Users/saito/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/saito/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/saito/.rvm/gems/ruby-2.2.0/gems/linner-0.9.1/lib/linner.rb:9:in `<top (required)>'
	from /Users/saito/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/saito/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/saito/.rvm/gems/ruby-2.2.0/gems/linner-0.9.1/bin/linner:10:in `<top (required)>'
	from /Users/saito/.rvm/gems/ruby-2.2.0/bin/linner:23:in `load'
	from /Users/saito/.rvm/gems/ruby-2.2.0/bin/linner:23:in `<main>'
	from /Users/saito/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/saito/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

Please release a new version of `reel`, maybe `v0.5.1` to lock the `http` to v0.7.x or fix this issue to release a new version of reel, maybe `v0.6.0`.

Thanks

**Comment by digitalextremist** [comment]
@SaitoWu I'll take care of this in `0.6.0.pre2`

**Comment by digitalextremist** [comment]
Can you please retest this with `0.6.0`?

**Comment by SaitoWu** [comment]
It works now! 

Thank you.
