### ISSUE TITLE
CLEANUP CRASHED! on Ctrl-C - JRuby / Windows environment

### ISSUE THREAD

**Issue by rjattrill** [celluloid/reel#210]
Running JRuby 1.7.22 in Windows environment with Reel 0.5.0, get the following crash on a Ctrl+C.

```
{I, [2015-10-06T13:34:09.304000 #4724]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
^C
C:\src\ec\rds>E, [2015-10-06T13:35:32.402000 #4724] ERROR -- : CLEANUP CRASHED!
IOError: closed stream
org/nio4r/Nio4r.java:188:in `deregister'
org/nio4r/Nio4r.java:422:in `close'
org/nio4r/Nio4r.java:413:in `close'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-io-0.17.2/lib/celluloid/io/reactor.rb:52:in `wait'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-io-0.17.2/lib/celluloid/io/reactor.rb:21:in `wait_readable'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-io-0.17.2/lib/celluloid/io.rb:53:in `wait_readable'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-io-0.17.2/lib/celluloid/io/tcp_server.rb:19:in `accept'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/reel-0.5.0/lib/reel/server.rb:38:in `run'
org/jruby/RubyKernel.java:1479:in `loop'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/reel-0.5.0/lib/reel/server.rb:38:in `run'
org/jruby/RubyKernel.java:1930:in `public_send'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-0.17.2/lib/celluloid/calls.rb:28:in `dispatch'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-0.17.2/lib/celluloid/call/async.rb:7:in `dispatch'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-0.17.2/lib/celluloid/cell.rb:50:in `dispatch'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-0.17.2/lib/celluloid/cell.rb:76:in `task'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-0.17.2/lib/celluloid/actor.rb:339:in `task'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-0.17.2/lib/celluloid/task.rb:44:in `initialize'
C:/opt/jruby-1.7.22/lib/ruby/gems/shared/gems/celluloid-0.17.2/lib/celluloid/task/fibered.rb:14:in `create'}
```

Some workarounds have been proposed by @digitalextremist here: https://github.com/kenichi/angelo/issues/56

**Comment by digitalextremist** [comment]
Solved in celluloid/celluloid-io#155
